/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v2

// MetricSourceReferenceApplyConfiguration represents a declarative configuration of the MetricSourceReference type for use
// with apply.
//
// MetricSourceReference identifies the API group of a metrics provider.
// The provider must serve the same wire format as the default provider
// for the metric type (MetricValueList for Pods/Object, ExternalMetricValueList
// for External).
type MetricSourceReferenceApplyConfiguration struct {
	APIGroup *string `json:"apiGroup,omitempty"`
}

// MetricSourceReferenceApplyConfiguration constructs a declarative configuration of the MetricSourceReference type for use with
// apply.
func MetricSourceReference() *MetricSourceReferenceApplyConfiguration {
	return &MetricSourceReferenceApplyConfiguration{}
}

// WithAPIGroup sets the APIGroup field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIGroup field is set to the value of the last call.
func (b *MetricSourceReferenceApplyConfiguration) WithAPIGroup(value string) *MetricSourceReferenceApplyConfiguration {
	b.APIGroup = &value
	return b
}
